spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    generate-unique-name: false
    name: myapp
    initialize: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql