management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${USR}
    password: ${PWD}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
