an: My new app
as: production in progress
cc:
  appName: My new app name
  appStatus: My new aoo status - production in progress

spring:
  datasource:
    url: postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:5432/${{PGDATABASE}}
    username: ${PGUSER}
    password: ${PGPASSWORD}
#"postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{PGDATABASE}}
  sql:
    init:
      mode: always